spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch14_product_management
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        ddl: none
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      timeout: 10s
      connect-timeout: 10s
      database: 0
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: "cache:product-service:"
      cache-null-values: true
      time-to-live: 600s

server:
  port: 8082
  servlet:
    context-path: /product-service

jwt:
  secret-key: T&5^P6TZ4FHnqJIGQ,cKhW]4>-Yax^hagdq3417235gasdfasgd6S5a4s65F
  expired-in: 3

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/